default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV['PG_HOST'] %>
  database: <%= ENV['PG_DB_DEVELOPMENT'] %>
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

test:
  <<: *default
  host: <%= ENV['PG_HOST'] %>
  database: <%= ENV['PG_DB_TEST'] %>
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

production:
  <<: *default
  database: vote-no-destino-prod
  username: vote-no-destino
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
